Black Woodmatt 21x 1mm:
  price_per_m: 0.85
  setup_cost: 20.0
Prime Oak Woodmatt 21x 1mm:
  price_per_m: 0.85
  setup_cost: 20.0
White 21x 1mm:
  price_per_m: 0.6
  setup_cost: 20.0
Colourboard 21x1mm:
  price_per_m: 0.8
  setup_cost: 20.0
