Finista Swift Drawer Kit High Drawer 172mm 500mm 40kg Matt White: FINISTA DRAWER SET
  172 MATT WHITE 500NL 40KG
Finista Swift Drawer Kit Mid Drawer 126mm 400mm 40kg Matt White: FINISTA DRAWER SET
  126 MATT WHITE 300NL 40KG
Finista Swift Drawer Kit Mid Drawer 126mm 500mm 40kg Matt White: FINISTA DRAWER SET
  126 MATT WHITE 500NL 40KG
Finista Swift Drawer Kit Standard Drawer 88mm 400mm 40kg Matt White: FINISTA DRAWER
  SET 88 MATT WHITE 400NL 40KG
Finista Swift Drawer Kit Super High Drawer 238mm 400mm 40kg Matt White: FINISTA DRAWER
  SET 238 MATT WHITE 400NL 40KG
Finista Swift Drawer Kit Super High Drawer 238mm 500mm 40kg Matt White: FINISTA DRAWER
  SET 238 MATT WHITE 400NL 40KG
Finista Swift Drawer Kit Super High Drawer 238mm mm 40kg Matt White: FINISTA DRAWER
  SET 238 MATT WHITE 400NL 40KG
Finista Swift Inner Drawer Kit High Drawer 172mm 500mm 40kg Matt White: FINISTA DRAWER
  SET 172 MATT WHITE 300NL 40KG
Finista Swift Inner Drawer Kit Standard Drawer 88mm 500mm 40kg Matt White: FINISTA
  DRAWER SET 88 MATT WHITE 500NL 40KG
Finista Swift Inner Drawer Kit Super High Drawer 238mm 500mm 40kg Matt White: FINISTA
  DRAWER SET 238 MATT WHITE 400NL 40KG
Hinge BLUM 110deg Full Overlay Inserta Onyx Black: Hinge BLUM 110deg Full Overlay
  Inserta
